import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const asyncMainCssPlugin = () => ({
  name: 'async-main-css',
  enforce: 'post',
  transformIndexHtml(html) {
    return html.replace(
      /<link rel="stylesheet"([^>]*href="\/assets\/index-[^"]+\.css"[^>]*)>/g,
      '<link rel="preload" as="style"$1 onload="this.onload=null;this.rel=\'stylesheet\'"><noscript><link rel="stylesheet"$1></noscript>',
    )
  },
})

// Two documents live in this project:
//   /            -> public/index.html, the static country-selection page,
//                   generated by scripts/build-landing.mjs (no React)
//   everything   -> app.html, the React shell
// In production Vercel does this routing (see vercel.json). This plugin does
// the same for `vite dev` and `vite preview` so both pages work locally.
const landingPagePlugin = () => {
  const middleware = (landingFile) => (req, res, next) => {
    const [pathname, query = ''] = (req.url || '/').split('?')
    const isNavigation = req.method === 'GET' && (req.headers.accept || '').includes('text/html')

    if (pathname === '/' || pathname === '/index.html') {
      const file = path.resolve(__dirname, landingFile)
      if (fs.existsSync(file)) {
        res.setHeader('Content-Type', 'text/html; charset=utf-8')
        res.end(fs.readFileSync(file))
        return
      }
      res.statusCode = 404
      res.end('Landing page not built yet. Run: node scripts/build-landing.mjs')
      return
    }

    const looksLikeFile = /\.[a-z0-9]+$/i.test(pathname)
    const isInternal = pathname.startsWith('/api') || pathname.startsWith('/@') || pathname.startsWith('/src/')
    if (isNavigation && !looksLikeFile && !isInternal) {
      req.url = '/app.html' + (query ? `?${query}` : '')
    }
    next()
  }

  return {
    name: 'landing-page-routing',
    configureServer(server) {
      server.middlewares.use(middleware('public/index.html'))
    },
    configurePreviewServer(server) {
      server.middlewares.use(middleware('dist/index.html'))
    },
  }
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(), asyncMainCssPlugin(), landingPagePlugin()],
  // No automatic fallback to index.html: the plugin above routes navigations
  // to app.html and keeps "/" for the static landing page.
  appType: 'mpa',
  server: {
    port: 3000,
    proxy: {
      '/ae-en/sitemap.xml': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
      '/ae-ar/sitemap.xml': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
      '/sitemap.xml': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
      '/api': {
        target: 'http://localhost:5000',
        changeOrigin: true,
      },
    },
  },
  build: {
    // Enable code splitting for better performance
    rollupOptions: {
      // The React shell. public/index.html (the landing page) is copied as-is.
      input: path.resolve(__dirname, 'app.html'),
      output: {
        manualChunks: {
          // Vendor chunks - separate large libraries
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-ui': ['lucide-react', 'react-icons'],
          'vendor-forms': ['react-hook-form', 'react-select'],
          'vendor-utils': ['axios'],
        },
      },
    },
    // Increase chunk size warning limit
    chunkSizeWarningLimit: 1000,
    // Enable minification (using esbuild - faster and built-in)
    minify: 'esbuild',
    esbuild: {
      drop: ['console', 'debugger'], // Remove console.logs and debugger in production
    },
    // Enable source maps for debugging (disable in production if needed)
    sourcemap: false,
  },
  // Optimize dependencies
  optimizeDeps: {
    include: ['react', 'react-dom', 'react-router-dom', 'axios'],
  },
})
