"use client"

import { useEffect } from "react"
import { X, Smartphone } from "lucide-react"
import TranslatedText from "./TranslatedText"

// The single QR opens the dedicated app-download page, which offers both stores and points a
// phone at the right one. It must be an absolute production URL so a phone scanning the code
// can reach it — a localhost link would be useless once printed or shown on another screen.
const DOWNLOAD_PAGE_URL = "https://www.grabatoz.ae/download-app.html"
const PLAY_STORE_URL = "https://play.google.com/store/apps/details?id=ae.grabatoz1.grabatoz1"
const APP_STORE_URL = "https://apps.apple.com/pk/app/graba2z/id6742447046"

// A QR image with high error correction (ecc=H) so the centred logo does not stop it
// scanning. Generated by a public QR service — no extra dependency to bundle.
const QR_SRC = `https://api.qrserver.com/v1/create-qr-code/?size=360x360&ecc=H&margin=1&data=${encodeURIComponent(
  DOWNLOAD_PAGE_URL,
)}`

/**
 * "Download Our App" modal opened from the navbar: one QR (with the Graba2z "G" in the
 * centre) that opens the mobile download page, plus the two store badges for desktop.
 */
const DownloadAppModal = ({ open, onClose }) => {
  useEffect(() => {
    if (!open) return
    const onKey = (e) => {
      if (e.key === "Escape") onClose()
    }
    document.addEventListener("keydown", onKey)
    const prevOverflow = document.body.style.overflow
    document.body.style.overflow = "hidden"
    return () => {
      document.removeEventListener("keydown", onKey)
      document.body.style.overflow = prevOverflow
    }
  }, [open, onClose])

  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-black/50 p-4 sm:items-center"
      role="dialog"
      aria-modal="true"
      onClick={onClose}
    >
      <div
        className="relative my-8 w-full max-w-md rounded-2xl bg-white shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          type="button"
          onClick={onClose}
          aria-label="Close"
          className="absolute right-3 top-3 z-10 rounded-full bg-white/80 p-1.5 text-gray-500 transition hover:bg-gray-100 hover:text-gray-800"
        >
          <X size={20} />
        </button>

        <div className="p-6 text-center">
          <div className="mx-auto mb-3 inline-flex items-center justify-center rounded-xl bg-lime-600 p-2 text-white">
            <Smartphone size={22} />
          </div>
          <h2 className="text-lg font-extrabold text-gray-900">
            <TranslatedText>Download Our App</TranslatedText>
          </h2>
          <p className="mt-1 text-sm text-gray-600">
            <TranslatedText>Scan with your phone camera to open the download page.</TranslatedText>
          </p>

          {/* One QR → the mobile download page (which offers both stores). */}
          <div className="mt-5 flex justify-center">
            <div className="relative rounded-2xl border-2 border-lime-200 bg-white p-3 shadow-sm">
              <img
                src={QR_SRC}
                alt="Scan to download the Graba2z app"
                width={220}
                height={220}
                className="h-[220px] w-[220px]"
              />
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="flex h-14 w-14 items-center justify-center rounded-xl border-2 border-lime-200 bg-white shadow-md">
                  <img
                    src="/g.png"
                    alt="Graba2z"
                    className="h-9 w-9 object-contain"
                    onError={(e) => {
                      e.currentTarget.style.display = "none"
                    }}
                  />
                </div>
              </div>
            </div>
          </div>

          <p className="mt-4 flex items-center justify-center gap-1.5 text-xs text-gray-500">
            <Smartphone size={13} />
            <TranslatedText>Available on Google Play and the App Store</TranslatedText>
          </p>

          {/* Desktop fallback — tap straight through to either store. */}
          <div className="mt-4 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <a href={PLAY_STORE_URL} target="_blank" rel="noreferrer" aria-label="Get it on Google Play">
              {/* The Play badge has little internal padding, so it needs a smaller height to
                  look the same size as the App Store badge next to it. */}
              <img src="/getitongoogle.png" alt="Get it on Google Play" className="h-10 w-auto" />
            </a>
            <a href={APP_STORE_URL} target="_blank" rel="noreferrer" aria-label="Download on the App Store">
              <img src="/getitonappstore.png" alt="Download on the App Store" className="h-12 w-auto" />
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}

export default DownloadAppModal
